name: Playwright Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Clean cache
      run: npm cache clean --force
    - name: Install Playwright Test
      run: npm install -D @playwright/test
    - name: Install Playwright
      run: npx playwright install
    - name: Install dotenv
      run: npm install dotenv --save
    - name: Run Playwright testFrontend01
      run: npm run testFrontend01
    - name: Clean cache
      run: npm cache clean --force
    - name: Run Playwright testFrontend02
      run: npm run testFrontend02
    - name: Clean cache
      run: npm cache clean --force
#    - name: Run Playwright testFrontend03
#      run: npm run testFrontend03
#    - name: Run Playwright testFrontend04
#      run: npm run testFrontend04
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
