name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install Newman
      run: npm install -g newman
    - name: Install Playwright Test
      run: npm install -D @playwright/test
    - name: Install Playwright
      run: npx playwright install
    - name: Install htmlextra
      run: npm install -g newman-reporter-htmlextra 
    - name: Install dotenv
      run: npm install dotenv --save
    - name: Run Playwright Backend Tests
      run: npm run testBackend
    - name: Run Playwright Frontend Tests
      run: npm run testFrontend01
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
